version: '3'

vars:
  SOLUTION_NAME: skunkworks    
  WEBAPI_NAME: shipyard_web
  APP_NAME: shipyard_app
  
tasks:

  logs:
    desc: "Tail shipyard logs"
    cmds:
      - docker logs {{.SOLUTION_NAME}}_{{.APP_NAME}}_1 -f --tail 100
      - docker logs {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 -f --tail 100
      
  sh:app:
    desc: "Connect to the shipyard-app shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.APP_NAME}}_1 bash

  sh:web:
    desc: "Connect to the shipyard-web shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 bash

  default:
    cmd:
      - task -l  