version: '3'

vars:
  SOLUTION_NAME: skunkworks      
  WEBAPI_NAME: shipyard_web
  WORKER_NAME: shipyard_worker
    
tasks:    

  logs:
    desc: "Show shipyard logs"
    cmds:
      - docker logs {{.SOLUTION_NAME}}_{{.WORKER_NAME}}_1 -f --tail 100
      - docker logs {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 -f --tail 100
      
  migrate:
    desc: "Run shipyard ef database migrations"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.WORKER_NAME}}_1 /tools/migration/Shipyard.Data.Migration

  rmi:
    desc: "Remove shipyard images"
    cmds:
      - cmd: docker image rmi shipyard-worker
        ignore_error: true
      - cmd: docker image rmi shipyard-worker:dev
        ignore_error: true        
      - cmd: docker image rmi shipyard-web
        ignore_error: true           
      - cmd: docker image rmi shipyard-web:dev
        ignore_error: true

  sh:worker:
    desc: "Connect to the shipyard-worker shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.WORKER_NAME}}_1 bash

  sh:web:
    desc: "Connect to the shipyard-web shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 bash

  default:
    cmds:
      - task -l
    