version: '3'

services:

  shipyard_web:    
    image: shipyard-web
    build: 
      context: ./sources/shipyard/
      dockerfile: src/Shipyard.Web/Dockerfile
    ports:
      - ${SHIPYARD_HTTP_PORT}:5000
      - ${SHIPYARD_HTTPS_PORT}:5001
    depends_on:
      - mssql
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  shipyard_worker:
    image: shipyard-worker
    build: 
      context: ./sources/shipyard
      dockerfile: src/Shipyard.Worker/Dockerfile
    depends_on:
      - mssql
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production        
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - ${MSSQL_PORT}:1433    
    # volumes:
    #   - mssql_data:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      

# volumes:
#   mssql_data: