version: '3'

services:

  shipyard_web:    
    image: shipyard-web
    build: 
      context: ./sources/shipyard/
      dockerfile: src/Shipyard.Web/Dockerfile
    ports:
      - ${SHIPYARD_HTTP_PORT}:5000
      - ${SHIPYARD_HTTPS_PORT}:5001
    depends_on:
      - mssql
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ConnectionStrings:Default=Server=mssql,${MSSQL_PORT};Database=skunkworks;User=sa;Password='${MSSQL_SA_PASSWORD}'

  shipyard_app:
    image: shipyard-app
    build: 
      context: ./sources/shipyard
      dockerfile: src/Shipyard.App/Dockerfile
    depends_on:
      - mssql
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production        

  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      