version: '3'

services:
  portauthority_web:    
    image: portauthority-web
    build: 
      context: ./sources/portauthority
      dockerfile: src/PortAuthority.Web/Dockerfile
    ports:
      - ${PORTAUTHORITY_HTTP_PORT}:80      
    depends_on:
      - mssql
      - rabbit
      - portauthority_dbmigrate
    environment:       
      - PathPrefix=/jobs/
      - ConnectionStrings__Rabbit=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbit/
      - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}

  portauthority_worker:
    image: portauthority-worker
    build: 
      context: ./sources/portauthority
      dockerfile: src/PortAuthority.Worker/Dockerfile
    depends_on:     
      - mssql
      - rabbit
      - portauthority_dbmigrate
    environment:       
      - ConnectionStrings__Rabbit=amqp://${RABBIT_USER}:${RABBIT_PASS}@rabbit/
      - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}

  portauthority_dbmigrate:    
    image: portauthority-dbmigrate
    command: dockerize -wait tcp://mssql:1433 -timeout 30s dotnet PortAuthority.Data.Migration.dll
    build: 
      context: ./sources/portauthority
      dockerfile: src/PortAuthority.Data.Migration/Dockerfile
    depends_on: 
      - mssql
    environment: 
      - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}
        
  # shipyard_web:    
  #   image: shipyard-web
  #   build: 
  #     context: ./sources/shipyard/
  #     dockerfile: src/Shipyard.Web/Dockerfile
  #   ports:
  #     - ${SHIPYARD_HTTP_PORT}:80      
  #   depends_on:
  #     - azstorage
  #     - mssql
  #     - rabbit
  #   environment: 
  #     - PathPrefix=/messaging/
  #     - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azstorage:10000/devstoreaccount1;
  #     - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}

  # shipyard_worker:
  #   image: shipyard-worker
  #   build: 
  #     context: ./sources/shipyard
  #     dockerfile: src/Shipyard.Worker/Dockerfile
  #   depends_on:     
  #     - azstorage  
  #     - mssql      
  #     - rabbit
  #     # - shipyard_db_migrate
  #   environment: 
  #     - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azstorage:10000/devstoreaccount1;    
  #     - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}

  # shipyard_db_migrate:    
  #   command: dockerize --tcp:1433 --wait 30s /app/Shipyard.Data.Migration
  #   depends_on: 
  #     - mssql
  #   environment: 
  #     - ConnectionStrings__SqlDatabase=Server=mssql;Database=skunkworks;User=sa;Password=${MSSQL_PASS}

  # azstorage:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   command: azurite-blob --blobHost 0.0.0.0
  #   ports:
  #     - ${AZSTORAGE_PORT}:10000

  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - ${MSSQL_PORT}:1433    
    volumes:
      - ./data/mssql/:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_PASS}

  nginx:
    image: nginx    
    ports:
      - ${NGINX_HTTP_PORT}:80      
    depends_on:
      - portauthority_web      
      #- shipyard_web
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/:/etc/nginx/conf.d    
      - ./services/nginx/sites-available/:/etc/nginx/sites-available
      - ./services/nginx/sites-enabled/:/etc/nginx/sites-enabled
  
  rabbit:
    image: rabbitmq:3.8-management-alpine   
    ports:
        - ${RABBIT_PORT}:15672
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}