version: "3"

services:
  shipyard_web:
    container_name: shipyard_web
    image: shipyard-web:latest
    build: 
      context: ./shipyard
      dockerfile: src/Shipyard.Web/Dockerfile
    ports:
       - 9000:9000
    # depends_on:
    #   - mssql

  # shipyard_app:
  #   build: 
  #     context: ./shipyard
  #     dockerfile: Dockerfile.app
  #   depends_on:
  #     - mssql      
        
  # mssql:
  #   image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=r00tp@ssw0rD
      