version: '3'

services:
  portauthority_web:    
    image: portauthority-web
    build: 
      context: ./sources/portauthority
      dockerfile: src/PortAuthority.Web/Dockerfile
    ports:
      - ${PORTAUTHORITY_HTTP_PORT}:80      
    depends_on:
      - mssql
    environment:       
      - PathPrefix=/jobs/
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  portauthority_worker:
    image: portauthority-worker
    build: 
      context: ./sources/portauthority
      dockerfile: src/PortAuthority.Worker/Dockerfile
    depends_on:     
      - mssql
      # - portauthority_db_migrate
    environment:       
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  # portauthority_db_migrate:    
  #   command: dockerize --tcp:1433 --wait 30s /app/Portauthority.Data.Migration
  #   depends_on: 
  #     - mssql
  #   environment: 
  #     - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}
        
  shipyard_web:    
    image: shipyard-web
    build: 
      context: ./sources/shipyard/
      dockerfile: src/Shipyard.Web/Dockerfile
    ports:
      - ${SHIPYARD_HTTP_PORT}:80      
    depends_on:
      - mssql
      - azstorage
    environment: 
      - PathPrefix=/messaging/
      - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://skunkworks_azstorage_1:10000/devstoreaccount1;
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  shipyard_worker:
    image: shipyard-worker
    build: 
      context: ./sources/shipyard
      dockerfile: src/Shipyard.Worker/Dockerfile
    depends_on:     
      - mssql
      - azstorage
      # - shipyard_db_migrate
    environment: 
      - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://skunkworks_azstorage_1:10000/devstoreaccount1;    
      - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  # shipyard_db_migrate:    
  #   command: dockerize --tcp:1433 --wait 30s /app/Shipyard.Data.Migration
  #   depends_on: 
  #     - mssql
  #   environment: 
  #     - ConnectionStrings__Default=Server=skunkworks_mssql_1;Database=skunkworks;User=sa;Password=${MSSQL_SA_PASSWORD}

  azstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - ${AZSTORAGE_PORT}:10000

  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - ${MSSQL_PORT}:1433    
    # volumes:
    #   - mssql_data:/var/opt/mssql/data/
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}

  nginx:
    image: nginx    
    ports:
      - ${NGINX_HTTP_PORT}:80      
    depends_on:
      - portauthority_web      
      - shipyard_web
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d/:/etc/nginx/conf.d    
      - ./services/nginx/sites-available/:/etc/nginx/sites-available
      - ./services/nginx/sites-enabled/:/etc/nginx/sites-enabled
  
  # rabbit:
  #   image: rabbitmap:3.8-management-alpine   

# volumes:
#   mssql_data: