version: "3"

services:
  shipyard_web:
    image: "shipyard-web:latest"
    build: 
      context: ./shipyard/
      dockerfile: web/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - sqldb

  shipyard_app:
    image: "shipyard-app:latest"
    build: 
      context: ./shipyard/
      dockerfile: app/Dockerfile    
    depends_on:
      - sqldb      
        
  sqldb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "r00tp@ssw0rD"
      ACCEPT_EULA: "Y"