version: '3'

includes:
  shipyard: ./shipyard
  #mssql: ./services/mssql
  #nginx: ./services/nginx

vars:
  SOLUTION_NAME: skunkworks
  SOLUTION_DIR:
    sh: pwd

tasks:
  
  up:
    desc: "Bring up the solution"
    cmds:
      - docker-compose -p {{.SOLUTION_NAME}} up -d --no-recreate

  down: 
    desc: "Bring down the solution"
    cmds:
      - docker-compose -p {{.SOLUTION_NAME}} stop
      - docker-compose -p {{.SOLUTION_NAME}} rm -f

  restart:
    desc: "Restart the solution"
    cmds:
      - task: down
      - task: up

  prune:
    desc: "Prune all dangling docker images"
    cmds:
      - docker images prune -a
    
  status:
    desc: "Display the status of all containers in the solution"
    cmds:
      - docker ps --format "table {{"{{"}}.ID{{"}}"}}\t{{"{{"}}.Names{{"}}"}}\t{{"{{"}}.Status{{"}}"}}\t{{"{{"}}.Image{{"}}"}}"

  log:
    desc: "Display logs for solution"
    cmds: 
      - docker-compose -p {{.SOLUTION_NAME}} logs -f --tail 100    

  logs:
    dep: [log]


  default:
    cmds:
      - task -l
