version: '3'

dotenv: ['.env']

silent: true

includes:  
  nginx: ./services/nginx
  azstorage: ./services/azurestorage
  mssql: ./services/sqlserver
  rabbit: ./services/rabbitmq  
  missioncontrol:
    taskfile: ./sources/missioncontrol/Taskfile.yml
    dir: ./sources/missioncontrol    
  portauthority:
    taskfile: ./sources/portauthority/Taskfile.yml
    dir: ./sources/portauthority    
  shipyard: 
    taskfile: ./sources/shipyard/Taskfile.yml
    dir: ./sources/shipyard
  

vars:
  SOLUTION_NAME: skunkworks
  SOLUTION_DIR:
    sh: pwd  
  SOLUTION_VERSION:
    sh: git rev-parse --short HEAD    

    
tasks:  
  init:
    deps: [ 
      init-az-credprovider, 
      init-docker-compose-override 
    ]
  
  init-az-credprovider:     
    dir: init
    cmds:
      - '{{if eq OS "windows"}}init-az-credprovider.cmd{{else}}init-az-credprovider.sh{{end}}'
    status:
      - test -d $HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft/

  init-docker-compose-override:
    cmds:
      - cp docker-compose.local.yml.example docker-compose.local.yml    
    status:
      - test -f docker-compose.local.yml
  
  up:
    desc: "Bring up the solution"
    deps: [ init  ]    
    cmds:
      - docker-compose -p {{.SOLUTION_NAME}} -f docker-compose.yml -f docker-compose.local.yml up -d --no-recreate

  down: 
    desc: "Bring down the solution"
    cmds:
      - docker-compose -p {{.SOLUTION_NAME}} stop
      - docker-compose -p {{.SOLUTION_NAME}} rm -f

  restart:
    desc: "Restart the solution"
    cmds:
      - task: down
      - task: up
  
  status:
    desc: "Display the status of all containers in the solution"
    cmds:
      - docker ps --format "table {{"{{"}}.ID{{"}}"}}\t{{"{{"}}.Names{{"}}"}}\t{{"{{"}}.Status{{"}}"}}\t{{"{{"}}.Image{{"}}"}}"

  log:
    desc: "Display logs for solution"
    cmds: 
      - docker-compose -p {{.SOLUTION_NAME}} logs -f --tail 100    

  logs:
    deps: [log]
    
  build:
    desc: "Builds all container images"
    cmds: 
      - docker-compose -p {{.SOLUTION_NAME}} build --force-rm

  push:
    desc: "Pushes container images to remote repositories"
    cmds:
      - docker-compose push

  pull:
    desc: "Pulls the most recent container images"
    cmds:
      - docker-compose pull
    
  pack:
    desc: "Package nugets"
    cmds:
      - task: portauthority:pack
      - task: shipyard:pack

  update-local-packages:
    deps: [ pack ]
    cmds:
      - task: portauthority:update-local-packages
      - task: shipyard:update-local-packages

  clear-local-packages:
    cmds:
      - task: portauthority:clear-local-packages
      - task: shipyard:clear-local-packages
    
  nuke:
    desc: "Nuke all data files and reset the solution"  
    deps: [ down ]
    cmds:
      - echo 'Pruning unused docker resources'
      - docker system prune -af
      - echo 'Deleting local service volume mounts ./data/'
      - rm -rf ./data/
      - echo 'Deleting local package feed ./packages/'
      - rm -rf ./packages/
    
  default:
    cmds:
      - task -l
