FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
EXPOSE 9000
ENV ASPNETCORE_URLS=http://*:9000
ENV DOTNET_USE_POLING_FILE_WATCHER=1

# Restore nuget packages into the dev image so that we don't
# duplicate effort and restore every time a new container is started
COPY ./ .
RUN [ "dotnet", "restore" ]

# Build development image, this assumes that ./shipyard is mounted as /app
ENTRYPOINT [ "dotnet", "watch", "--project", "src/Shipyard.Web", "run" ]