version: '3'

vars:
  SOLUTION_NAME: skunkworks    
  WEBAPI_NAME: shipyard_web
  APP_NAME: shipyard_app
  
tasks:

  logs:
    desc: "Show all logs"
    cmds:
      - task: logs:app
      - task: logs:web
  
  logs:app:
    desc: "Show shipyard-app logs"
    cmds:
      - docker logs {{.SOLUTION_NAME}}_{{.APP_NAME}}_1 -f --tail 100

  logs:web:
    desc: "Show shipyard-web logs"
    cmds:
      - docker logs {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 -f --tail 100
      
  sh:app:
    desc: "Connect to shipyard-app shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.APP_NAME}}_1 bash

  sh:web:
    desc: "Connect to shipyard-web shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.WEBAPI_NAME}}_1 bash

  default:
    cmd:
      - task -l  