version: '3'

vars:
  PA_WEBAPI_NAME: portauthority_web
  PA_WORKER_NAME: portauthority_worker
    
tasks:    
  pack:
    cmds:      
      - mkdir -p "{{.SOLUTION_DIR}}/packages"
      - dotnet pack src/PortAuthority.Contracts -c Release -o ./artifacts      
      - dotnet nuget push ./artifacts/*.nupkg -s "{{.SOLUTION_DIR}}/packages"

  update-local-packages:
    cmds:      
      - dotnet nuget locals all --clear
      - cp "{{.SOLUTION_DIR}}/packages/*.nupkg" packages/
    
  clear-local-packages:
    cmds:
      - dotnet nuget locals all --clear
      - rm -rf "{{.SOLUTION_DIR}}/packages/PortAuthority*.nupkg"      
      - rm -rf packages/*.nupkg
      - rm -rf artifacts/*.nupkg      
    
  log:
    desc: "Show portauthority logs"
    cmds:
      - docker logs {{.SOLUTION_NAME}}_{{.PA_WEBAPI_NAME}}_1 -f --tail 100
      - docker logs {{.SOLUTION_NAME}}_{{.PA_WORKER_NAME}}_1 -f --tail 100

  logs:
    deps: [log]

  restart:
    desc: "Restart this service"
    cmds:
      - cmd: docker rm -f {{.SOLUTION_NAME}}_{{.PA_WEBAPI_NAME}}_1
        ignore_error: true
      - cmd: docker rm -f {{.SOLUTION_NAME}}_{{.PA_WORKER_NAME}}_1
        ignore_error: true        
      - task: :up

  sh:worker:
    desc: "Connect to the portauthority-worker shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.PA_WORKER_NAME}}_1 bash

  sh:web:
    desc: "Connect to the portauthority-web shell"
    cmds:
      - docker exec -it {{.SOLUTION_NAME}}_{{.PA_WEBAPI_NAME}}_1 bash
      
  dbmigrate:
    desc: "Run database migrations"
    cmds:
      - docker build -t portauthority-dbmigrate:latest -f src/PortAuthority.Data.Migration/Dockerfile .
      - docker run --rm -it --network={{.SOLUTION_NAME}}_default portauthority-dbmigrate:latest

  loadtest:
    desc: "Run k6 load tests"
    dir: ./test/PortAuthority.k6/
    cmds:
      - docker build -t portauthority-k6:latest .
      - docker run --rm -it --network={{.SOLUTION_NAME}}_default portauthority-k6:latest
      
  rmi:
    desc: "Remove portauthority images"
    cmds:
      - cmd: docker image rmi portauthority-worker
        ignore_error: true
      - cmd: docker image rmi portauthority-worker:dev
        ignore_error: true        
      - cmd: docker image rmi portauthority-web
        ignore_error: true           
      - cmd: docker image rmi portauthority-web:dev
        ignore_error: true
      - cmd: docker image rmi portauthority-dbmigrate
        ignore_error: true
      - cmd: docker image rmi portauthority-dbmigrate:dev
        ignore_error: true
      
  default:
    cmds:
      - task -l
    